package de.dengot.hl2stats.logic;

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Oct 04 09:11:34 CEST 2005
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface HL2LogSymbols {
  /* terminals */
  public static final int HEALTH = 10;
  public static final int TIME = 16;
  public static final int DATE = 15;
  public static final int HEADSHOT = 4;
  public static final int NUMBER = 2;
  public static final int DAMAGE = 8;
  public static final int DAMAGE_ARMOR = 9;
  public static final int STRING_LITERAL = 3;
  public static final int EOF = 0;
  public static final int KILLED = 6;
  public static final int OPEN_BRACKET = 13;
  public static final int ARMOR = 11;
  public static final int CLOSE_BRACKET = 14;
  public static final int error = 1;
  public static final int WITH = 7;
  public static final int ATTACKED = 5;
  public static final int HITGROUP = 12;
}

